# Spring Boot application properties for the backend service
spring.application.name=backend

# Import environment variables from .env.local file
spring.config.import=optional:file:../../.env.local

# Database configuration
spring.datasource.url=jdbc:postgresql://database:5432/recipe_maker_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.access-token.expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt.refresh-token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}